// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyHostsPlan(arg1, arg2) {
  return window['go']['main']['App']['ApplyHostsPlan'](arg1, arg2);
}

export function DeleteStoredGroup(arg1) {
  return window['go']['main']['App']['DeleteStoredGroup'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LastStoredHostsFile() {
  return window['go']['main']['App']['LastStoredHostsFile']();
}

export function LoadStoredGroups() {
  return window['go']['main']['App']['LoadStoredGroups']();
}

export function PreviewHostsSelection(arg1, arg2) {
  return window['go']['main']['App']['PreviewHostsSelection'](arg1, arg2);
}

export function SaveHostsSelection(arg1, arg2) {
  return window['go']['main']['App']['SaveHostsSelection'](arg1, arg2);
}

export function SaveStoredGroups(arg1) {
  return window['go']['main']['App']['SaveStoredGroups'](arg1);
}

export function SelectHostsFile() {
  return window['go']['main']['App']['SelectHostsFile']();
}
