// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {main} from '../models';

export function DeleteStoredGroup(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function LastStoredHostsFile():Promise<string>;

export function LoadStoredGroups():Promise<Array<storage.Group>>;

export function SaveHostsSelection(arg1:string,arg2:Array<main.SaveHostsSelectionItem>):Promise<main.ParsedHostsSelection>;

export function SaveStoredGroups(arg1:Array<storage.Group>):Promise<void>;

export function SelectHostsFile():Promise<main.ParsedHostsSelection>;
